### ISSUE TITLE
工作经历无法填写

### ISSUE THREAD

**Issue by dashingli** [visiky/resume#89]
error
11react_devtools_backend_compact.js:2367 TypeError: t.work_time.split is not a function
    at component---src-pages-index-tsx-334b29b7b50dc66c3d04.js:2:684398
    at onFinish (component---src-pages-index-tsx-334b29b7b50dc66c3d04.js:2:309756)
    at component---src-pages-index-tsx-334b29b7b50dc66c3d04.js:2:307561
o

**Comment by n-WN** [comment]
+1 我最后是保存 JSON ,改 JSON 后导入配置报错, 不过审查元素去掉无关后依旧可以导出 pdf

**Comment by luosheep2020** [comment]
我看了一下console，时间分隔那里不能用逗号
